#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults10-stalwart
PROCESS_NAME="stalwart-config-reload"

check_container_initialized
check_service_initialized init

liftoff

while inotifywait -q -e create,delete,modify,attrib "$(set -o posix ; set | grep -P "^TLS_.*_FILE" | sort -u | cut -d = -f2 | tr '\n' ' ')" ; do
    if pidof 2&>1 stalwart-mail ; then
        print_info "Reloading Stalwart Mail configuration do to a detected certificate change"
        sudo -u "${SERER_USER}" stalwart-mail -u ${JMAP_LISTENER_JMAP_URL} server reload-certificates
        exit 0
    fi
    sleep 5
done