#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="stalwart"

setup_container_mode
bootstrap_filesystem
configure_common

custom_files "${CONTAINER_CUSTOM_PATH}" /
custom_scripts "${CONTAINER_CUSTOM_SCRIPTS_PATH}"
liftoff
