#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="stalwart"
prepare_service defaults single

check_container_initialized
check_service_initialized init

liftoff

print_start "Starting Stalwart ${STALWART_VERSION}"
silent exec stalwart-mail \
                            --config "${CONFIG_PATH}"/"${CONFIG_FILE}"
